version: "3"
services:
    php-fpm:
        image: php:7.2-fpm
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: demo
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: demo
            MYSQL_PASSWORD: password

